--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MengBaofh/MEBsociety
build-by-default: true
branches:
- master
projects:
  MEBsociety:
    path: ""
    icon: "MEBS2.png"
    lint:
      phpstan: false
...
